plugins {
    id 'com.android.application'
}

android {
    namespace 'com.uwright.wirebrowser'
    compileSdk 35

    defaultConfig {
        applicationId 'com.uwright.wirebrowser'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
